services:
  azurite:
    container_name: azurite-mysql-test
    hostname: azurite
    build:
      context: test-containers/azurite
      dockerfile: Dockerfile
      args:
        AZURITE_VERSION: ${AZURITE_VERSION}
        AZURE_STORAGE_BLOB_VERSION: ${AZURE_STORAGE_BLOB_VERSION}
    command: sh -c "sh /run.sh | azurite -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --loose --skipApiVersionCheck"
    environment:
      AZURE_STORAGE_ACCOUNT: devstoreaccount1
      AZURE_STORAGE_ACCESS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      COMMA_SEPARATED_CONTAINER_NAMES: "mlflow"
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./test-containers/azurite/create-container.js:/create-container.js
      - ./test-containers/azurite/run.sh:/run.sh
    networks:
      - azure_mysql_test_nw

  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mlflow-azure-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mlflow
      MYSQL_USER: mlflow
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - azure_mysql_test_nw

  mlflow:
    container_name: mlflow-azure-mysql-test
    build:
      context: .
      dockerfile: Dockerfile
    command: "mlflow server --backend-store-uri=mysql+pymysql://mlflow:password@mysql:3306/mlflow --default-artifact-root=wasbs://mlflow@devstoreaccount1.blob.core.windows.net --host=0.0.0.0 --port=8080"
    environment:
      MLFLOW_FLASK_SERVER_SECRET_KEY: 0123456789
      MLFLOW_DISABLE_TELEMETRY: "true"
      DO_NOT_TRACK: "true"
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1
    ports:
      - "8080:8080"
    networks:
      - azure_mysql_test_nw
    depends_on:
      mysql:
        condition: service_healthy

networks:
  azure_mysql_test_nw:
    driver: bridge
