services:
  minio:
    container_name: minio-basic-auth-test
    hostname: minio
    image: minio/minio:${MINIO_VERSION}
    entrypoint: sh
    command: -c 'mkdir -p /data/mlflow && minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-basic-auth-storage:/data
    networks:
      - basic_auth_test_nw

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: mlflow-basic-auth-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-basic-auth-storage:/var/lib/postgresql/data
    networks:
      - basic_auth_test_nw

  usersdb:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: mlflow-basic-auth-users-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres-basic-auth-users-storage:/var/lib/postgresql/data
    networks:
      - basic_auth_test_nw

  mlflow:
    container_name: mlflow-basic-auth-test
    build:
      context: .
      dockerfile: Dockerfile
    command: "mlflow server --backend-store-uri=postgresql:// --default-artifact-root=s3://mlflow/ --host=0.0.0.0 --port=8080 --app-name basic-auth"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: mlflow
      PGUSER: postgres
      PGPASSWORD: postgres
      MLFLOW_AUTH_CONFIG_PATH: /mlflow/basic_auth.ini
    ports:
      - "8080:8080"
    networks:
      - basic_auth_test_nw
    volumes:
      - mlflow-basic-auth-storage:/mlflow
      - ./test-containers/basic-auth/basic_auth.ini:/mlflow/basic_auth.ini
    depends_on:
      - minio
      - postgres
      - usersdb

volumes:
  postgres-basic-auth-storage:
    driver: local
  postgres-basic-auth-users-storage:
    driver: local
  mlflow-basic-auth-storage:
    driver: local
  minio-basic-auth-storage:
    driver: local

networks:
  basic_auth_test_nw:
    driver: bridge
