# Stage 1: Build and dependencies
FROM python:3.13.9 AS foundation

# Create necessary symlinks
RUN ln -s /usr/bin/dpkg-split /usr/sbin/dpkg-split \
    && ln -s /usr/bin/dpkg-deb /usr/sbin/dpkg-deb \
    && ln -s /bin/rm /usr/sbin/rm \
    && ln -s /bin/tar /usr/sbin/tar

# Install required build tools and libraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      make \
      build-essential \
      libssl-dev \
      zlib1g-dev \
      libbz2-dev \
      libreadline-dev \
      libsqlite3-dev \
      wget \
      curl \
      libncursesw5-dev \
      xz-utils \
      tk-dev \
      libxml2-dev \
      libxmlsec1-dev \
      libffi-dev \
      liblzma-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/* /var/log/* /tmp/* /var/tmp/*

WORKDIR /mlflow-build/

# Copy only necessary files for dependency installation
COPY pyproject.toml poetry.toml poetry.lock LICENSE README.md ./
COPY mlflowstack ./mlflowstack

# Upgrade pip and install Poetry with no cache
RUN python -m pip install --upgrade pip --no-cache-dir && \
    pip install poetry wheel --no-cache-dir

# Install project dependencies without development tools
RUN poetry build

WORKDIR /mlflow/

RUN python -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir /mlflow-build/dist/mlflowstack-*.whl

# Stage 2: Final slim image
FROM python:3.13.9-slim

LABEL maintainer="Burak Ince <burak.ince@linux.org.tr>"

# Create a non-root mlflow user and group
RUN groupadd -r -g 1001 mlflow && useradd -r -u 1001 -g mlflow -m -d /home/mlflow mlflow

WORKDIR /mlflow/

# Set ownership of the mlflow directory to the mlflow user
RUN chown -R mlflow:mlflow /mlflow

# Copy the virtual environment from the foundation stage and set ownership
COPY --from=foundation --chown=mlflow:mlflow /opt/venv /opt/venv

# Activate venv
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

# Switch to non-root user
USER mlflow

EXPOSE 5000

# Default command to run MLflow server
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.sqlite", "--default-artifact-root", "./mlruns", "--host=0.0.0.0", "--port=5000"]
