version: "3.8"

services:
  azurite:
    container_name: azurite-pg-test
    hostname: azurite
    build:
      context: test-containers/azurite
      dockerfile: Dockerfile
    command: sh -c "sh /run.sh | azurite -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --loose --skipApiVersionCheck"
    environment:
      AZURE_STORAGE_ACCOUNT: devstoreaccount1
      AZURE_STORAGE_ACCESS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      COMMA_SEPARATED_CONTAINER_NAMES: "mlflow"
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - azurite-pg-storage:/data
      - ./test-containers/azurite/create-container.js:/create-container.js
      - ./test-containers/azurite/run.sh:/run.sh
    networks:
      - azure_pg_test_nw

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: mlflow-azure-postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-azure-storage:/var/lib/postgresql/data
    networks:
      - azure_pg_test_nw

  mlflow:
    container_name: mlflow-azure-pg-test
    build:
      context: .
      dockerfile: Dockerfile
    command: "mlflow server --backend-store-uri=postgresql:// --default-artifact-root=wasbs://mlflow@devstoreaccount1.blob.core.windows.net --host=0.0.0.0 --port=8080"
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - azure_pg_test_nw
    volumes:
      - mlflow-azure-pg-storage:/mlflow
    depends_on:
      - azurite
      - postgres

volumes:
  postgres-azure-storage:
    driver: local
  mlflow-azure-pg-storage:
    driver: local
  azurite-pg-storage:
    driver: local

networks:
  azure_pg_test_nw:
    driver: bridge
